name: publish

on:
  release:
    types: published
  push:
    branches: master

env:
  NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: borales/actions-yarn/@v2.0.0
      with:
        cmd: install
    - name: Build & publish
      run: |
        npm run build
        NPM_TOKEN=${{ secrets.NPM_ACCESS_TOKEN }} npm publish
